# Generated by Django 3.0.2 on 2020-06-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_help'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Help Article', 'verbose_name_plural': 'Help Articles'},
        ),
    ]
