# Generated by Django 3.0.2 on 2020-05-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='googleTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='File Title')),
                ('filename', models.CharField(blank=True, default='', max_length=150, verbose_name='Upload File')),
                ('status', models.CharField(blank=True, choices=[('A', 'A'), ('I', 'I')], default='', max_length=1)),
                ('time', models.TimeField(blank=True, default='', max_length=150)),
            ],
        ),
    ]
