# Generated by Django 3.0.2 on 2020-05-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleTrend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletrend',
            name='filename',
            field=models.FileField(blank=True, default='', max_length=150, upload_to='trend_files', verbose_name='Upload File'),
        ),
    ]
