# Generated by Django 3.0.2 on 2020-06-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleTrend', '0002_auto_20200525_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletrend',
            name='filename',
            field=models.FileField(blank=True, default='', max_length=150, upload_to='trend_files/', verbose_name='Upload File'),
        ),
        migrations.AlterField(
            model_name='googletrend',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], default='', max_length=1),
        ),
    ]
