# Generated by Django 3.0.2 on 2020-06-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleTrend', '0003_auto_20200610_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googletrend',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
