# Generated by Django 3.0.2 on 2020-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleTrend', '0004_auto_20200615_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrend',
            name='query_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
