# Generated by Django 3.0.2 on 2020-08-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleTrend', '0005_googletrend_query_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googletrend',
            name='status',
        ),
        migrations.RemoveField(
            model_name='googletrend',
            name='time',
        ),
    ]
