# Generated by Django 3.0.5 on 2020-05-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('tablename', models.CharField(blank=True, default='', max_length=30)),
                ('recordid', models.IntegerField(blank=True, default='')),
                ('recordname', models.TextField(default='')),
            ],
        ),
    ]
