# Generated by Django 3.0.5 on 2020-05-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortURL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ShortURL',
            table='ShortURL',
        ),
    ]
