# Generated by Django 3.0.5 on 2020-05-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortURL', '0002_auto_20200513_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ShortURL',
            name='tablename',
            field=models.CharField(blank=True, choices=[('user_excel_data', 'User Excel Data'), ('news', 'News'), ('tab_video', 'Video'), ('categories', 'Categories')], default='', max_length=30),
        ),
    ]
