# Generated by Django 3.0.5 on 2020-05-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortURL', '0003_auto_20200513_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ShortURL',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], default='I', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='ShortURL',
            unique_together={('code', 'tablename')},
        ),
    ]
