# Generated by Django 3.0.5 on 2020-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortURL', '0004_auto_20200513_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ShortURL',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], default='A', max_length=1),
        ),
    ]
