# Generated by Django 3.0.5 on 2020-05-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortURL', '0005_auto_20200513_1313'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ShortURL',
            table='shortURL',
        ),
    ]
