# Generated by Django 3.0.2 on 2020-06-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('path', models.TextField(default=None)),
                ('status', models.CharField(choices=[('A', 'A'), ('I', 'I')], default='I', max_length=1)),
                ('section', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
