# Generated by Django 3.0.2 on 2020-06-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportFiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfiles',
            name='filename',
            field=models.FileField(blank=True, default='', max_length=150, upload_to='report_files/', verbose_name='Upload File'),
        ),
    ]
