# Generated by Django 3.0.2 on 2020-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportFiles', '0002_reportfiles_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfiles',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
