# Generated by Django 3.0.2 on 2020-06-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportFiles', '0003_auto_20200610_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfiles',
            name='path',
        ),
    ]
