# Generated by Django 3.0.2 on 2020-06-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportFiles', '0004_remove_reportfiles_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfiles',
            name='status',
            field=models.CharField(choices=[('A', 'A'), ('I', 'I')], default='A', max_length=1),
        ),
        migrations.AlterModelTable(
            name='reportfiles',
            table='reportfiles',
        ),
    ]
