# Generated by Django 3.0.2 on 2020-06-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportFiles', '0005_auto_20200611_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportfiles',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
