# Generated by Django 3.0.2 on 2020-06-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_query_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchqueryalalysis',
            name='input_data',
            field=models.FileField(blank=True, default='', help_text='Upload CSV file for Input Data', max_length=150, upload_to='query_analysis_files/', verbose_name='Input Data File'),
        ),
        migrations.AlterField(
            model_name='searchqueryalalysis',
            name='lookup_words_no_convs',
            field=models.FileField(blank=True, default='', help_text='Upload CSV file for Lookup Words No Convs', max_length=150, upload_to='query_analysis_files/', verbose_name='Lookup Words No Convs'),
        ),
    ]
