# Generated by Django 3.0.2 on 2020-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='googlesearchresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Google Search Result Analysis',
                'verbose_name_plural': 'Google Search Result Analysis',
                'db_table': 'google_search_result',
            },
        ),
    ]
