# Generated by Django 3.0.2 on 2020-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresult',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
