# Generated by Django 3.0.2 on 2020-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0002_googlesearchresult_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresult',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
    ]
