# Generated by Django 3.0.2 on 2020-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0003_googlesearchresult_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesearchresult',
            options={'verbose_name': 'Google Search Result ', 'verbose_name_plural': 'Google Search Result '},
        ),
        migrations.AddField(
            model_name='googlesearchresult',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
