# Generated by Django 3.0.2 on 2020-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0004_auto_20200626_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesearchresult',
            name='search_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
