# Generated by Django 3.0.2 on 2020-06-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0005_auto_20200627_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesearchresult',
            options={'verbose_name': 'Search Query ', 'verbose_name_plural': 'Search Query'},
        ),
        migrations.CreateModel(
            name='googlesearchresultData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(max_length=150)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
                ('keyword_density', models.CharField(blank=True, max_length=50, null=True)),
                ('url_keyword_density', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlesearchresult', to='googlesearchresult.googlesearchresult')),
            ],
            options={
                'verbose_name': 'Search Query Data',
                'verbose_name_plural': 'Search Query Data',
                'db_table': 'google_search_result_data',
            },
        ),
    ]
