# Generated by Django 3.0.2 on 2020-06-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0006_auto_20200627_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesearchresultdata',
            name='custom_url',
        ),
        migrations.RemoveField(
            model_name='googlesearchresultdata',
            name='file_path',
        ),
    ]
