# Generated by Django 3.0.2 on 2020-06-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0008_auto_20200627_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='search_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
