# Generated by Django 3.0.2 on 2020-07-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0009_googlesearchresultdata_search_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='individual_keyword_density',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresult',
            name='custom_url',
            field=models.CharField(blank=True, help_text='And a URL you would like to compare the keyword density.   You must include http:// or https://', max_length=255, null=True),
        ),
    ]
