# Generated by Django 3.0.2 on 2020-07-02 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0010_auto_20200702_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='file_path',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='keywordDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.CharField(blank=True, max_length=50, null=True)),
                ('keyword_density', models.CharField(blank=True, max_length=50, null=True)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='googlesearchresult.googlesearchresultData')),
            ],
            options={
                'verbose_name': 'Keyword Density',
                'verbose_name_plural': 'Keyword Density',
                'db_table': 'keyword_density',
            },
        ),
    ]
