# Generated by Django 3.0.2 on 2020-07-03 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0011_auto_20200702_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyworddensity',
            name='rec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlesearchresultData', to='googlesearchresult.googlesearchresultData'),
        ),
    ]
