# Generated by Django 3.0.2 on 2020-07-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0013_auto_20200710_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlesearchresultdata',
            old_name='serach_position',
            new_name='search_position',
        ),
    ]
