# Generated by Django 3.0.2 on 2020-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0016_auto_20200713_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='all_title',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='bodytext',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='h1_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='h2_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='h3_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='h4_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='h5_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='h6_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='url_meta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='url_title',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
