# Generated by Django 3.0.2 on 2020-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0017_auto_20200714_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='individual_keyword_density',
            field=models.CharField(blank=True, help_text='And  lkjflkfjkldsjfjdskfjkldjf', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchresultdata',
            name='keyword_density',
            field=models.CharField(blank=True, help_text='And ', max_length=50, null=True),
        ),
    ]
