# Generated by Django 3.0.2 on 2020-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0018_auto_20200717_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='suggest_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='suggest_key_density',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
