# Generated by Django 3.0.2 on 2020-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlesearchresult', '0019_auto_20200730_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesearchresultdata',
            name='tagstatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
